[workspace]
resolver = "2"

members = [
    "domino",
	"domino-cli",
]

[workspace.dependencies]
tokio = "1"
tonic = "0.10"
tonic-reflection = "0.10"
prost = "0.12"
# build-dependencies
winres = "0.1"
tonic-build = "0.10"

[profile.release]
codegen-units = 1
lto = true
strip = true
